### PR TITLE
use @cycle/storage

### PR DESCRIPTION
**Pull request by khalillechelt**
Not ready to merge yet.

### CODE REVIEW

**Comment by khalillechelt** [comment]
Anyway, sorry for the broken PR earlier @staltz. I'll see to fixing this as soon as possible.

**Comment by khalillechelt** [comment]
OK @staltz, for some reason my changes to cycle/storage (which was just a refactoring basically, so I don't know if that is really because of my changes) introduced a race condition so that `.merge()` and `.scan()` did not provide the desired result. First all the modification-functions came through and then the todoData. I changed it to using `.combineLatest()` and `.map()` and it seems to work for me now.

Can you have a look at the change (https://github.com/kahlil/todomvc-cycle/commit/86351eecc94fd362e03ac65bf9564e8eca81edef#diff-2e064487718803adeada2cb9831822c7R109) and let me know if this is OK?

**Comment by khalillechelt** [comment]
Morning @staltz do you have a plan on how to proceed with this?

**Comment by staltz** [comment]
Hi, I've been really short of time lately.

> I changed it to using .combineLatest() and .map() and it seems to work for me now.

We definitely need to keep it as merge+scan. combineLatest might fix the problem in this specific case, but in general it's proven (in my experience) to be the wrong combinator to manage state in the model.

About going forward, we can either wait until Saturday when I have to time to work on all things Cycle related, or you can try doing the fixes yourself with my support. At first, I think we can try this: maybe combineLatest worked because it buffers the latest value, and merge doesn't. So if sourceTodosData$ is hot, merge won't buffer the value. So what you can do instead is use shareReplay on the sourceTodosData$ before merging+scanning it.

**Comment by khalillechelt** [comment]
Understood.
I'd really like to fix this myself with your support. Thanks for the input I'll try that out!

**Comment by khalillechelt** [comment]
Ok shareReplay does not seem to change anything. 

On an empty localStorage these are the three data items coming through when we merge the localstorage stream with the modification stream: 

``` js
function (todosData) {
      todosData.filter = route.replace('/', '').trim();
      todosData.filterFn = filterFn;
      return todosData;
}
// ---
function (todosData) {
      todosData.filter = route.replace('/', '').trim();
      todosData.filterFn = filterFn;
      return todosData;
}
// ---
Object {list: Array[0], filter: ""}
```

it really should be 

``` js
Object {list: Array[0], filter: ""}
//---
function (todosData) {
      todosData.filter = route.replace('/', '').trim();
      todosData.filterFn = filterFn;
      return todosData;
    }
```

Any idea on why that is happening?

**Comment by khalillechelt** [comment]
Honestly I have to work a little more on the understanding of the mechanics you had implemented here in the first place. I am a little stumped with this right now... Gonna dive in :smile:

**Comment by khalillechelt** [comment]
@staltz OK after poking around the problem to me, does look like a race condition. I made the storage driver somewhat DRYer in the last update which seems to have the effect to make the localStorage come through just a little less quicker. It should be the first data coming through the merged Observables but it is the last. Is there any elegant way to merge them in a way so that the localStorage data is guaranteed to comes through first?

**Comment by staltz** [comment]
> Is there any elegant way to merge them in a way so that the localStorage data is guaranteed to comes through first?

concat operator usually does that.

**Comment by khalillechelt** [comment]
Cool, I'll try that out.

**Comment by khalillechelt** [comment]
That fixed it! \o/

I had actually tried `concat` before but I forgot to do `.take(1)` on the `localStorage$` so it crashed the browser with an endlessly concatenating loop :grinning: 
I also was not confident trying other methods since it sounded like you wanted this solved with `merge`+`scan`. So thanks for pointing me in the right direction! 

This works now and I think it actually describes what is happening a little better, since `scan` really requires the localStorage data to come first in order to work properly.

You can verify this working by checking out this branch and doing an `npm install && npm start`.

Thanks for taking out the time to help me!

**Comment by khalillechelt** [comment]
Does this need to be changed in order to work with Cycle.js 2.0?

**Comment by staltz** [comment]
> Does this need to be changed in order to work with Cycle.js 2.0?

Thanks @kahlil for your patience, you don't need to change much since I already had todomvc for Cycle Nested in a separate branch which I just merged. I've been slow to merge this because I'm flooded with things to do and todomvc is an important example that must be done perfectly. In other cases I merge PRs more easily. Since you said this is now working, I'll attempt to merge manually.

**Comment by khalillechelt** [comment]
OK, sounds great. I am excited to see this being merged in soon.
No problem by the way, I am well aware of the mountain of work you are faced with because of the new release.

**Comment by staltz** [comment]
Finally merged! Super thanks!

**Comment by khalillechelt** [comment]
Yeeeey! \o/ awesome!

**Pull request merged**
