### PR TITLE
Test todo title getting undefined after edit

### LINKED ISSUE #39: confirming the edition of a task yields an empty task
Steps to reproduce:

1. start the app
2. create a task (say '123')
3. double click on the created task to edit it (say you change it from '123' to '12345')
4. press Enter to confirm the edition

Expected result: task in "non-edited" mode with the label '12345'

Actually observed: empty task

### PR DESCRIPTION
**Pull request by hgwood**
~~Closes #39~~ Adds a test or the scenario described in issue #39.

I took the opportunity to add a minimal test harness based on [tape](https://www.npmjs.com/package/tape).

### CODE REVIEW

**Comment by staltz** [comment]
Hi @hgwood :)
Thanks for submitting this PR, we appreciate any kind of desire to help. Before merging this PR could you notice that the latest version of this TodoMVC is under the branch `onionify`. We should merge it to master soon, when onionify v4 is launched. Could you make this PR against that branch? I'm not even sure if the bug would still occur in the branch.

**Comment by hgwood** [comment]
Hello @staltz (should have said that first, sorry). Thank you for your kind reply and pointers. After a quick look at the code, it seems the bug is indeed fixed in the `onionify` branch. I will confirm by rebasing and running the test later. Would you still be interested in merging the test into `onionify`?

**Comment by hgwood** [comment]
I have changed the test to match the new app. It does show the bug is fixed.

**Comment by staltz** [comment]
Hi @hgwood, thanks for the interesting test to keep this bug from returning. (I'm going through dozens of issues and PRs)

I would merge this, but as a single isolated test it may feel odd to someone browsing the source code when learning this. So I'll leave this PR open, you can choose whether to close it or add more comprehensive tests so that the whole codebase is tested.

**Comment by hgwood** [comment]
I understand. I will close it in favor of other priorities. Thank you for your consideration.

**Pull request closed without merging**
