### PR TITLE
use @cycle/storage

### PR DESCRIPTION
**Pull request by khalillechelt**
Here my update using `@cycle/storage`. 
I also added an `npm start` script that watchifies the scripts and starts a live reload server.

### CODE REVIEW

**Comment by staltz** [comment]
Looks good, thanks @kahlil ! (I finally reviewed it)

**Comment by khalillechelt** [comment]
:+1:

**Comment by staltz** [comment]
Forgot to add `@cycle/storage` to package.json, but I'm doing that now.

**Comment by khalillechelt** [comment]
ah. thanks!

**Comment by staltz** [comment]
Actually, I'm going to revert the merge of this PR because I got some problems. I should have merged your PR to another branch, but I merged it to master. Can you resubmit and we can iterate on its fixes?

**Comment by khalillechelt** [comment]
OK, will do.

**Comment by khalillechelt** [comment]
argh OK, I made some changes to storage after sending this PR. I'll re-send the PR, but I am happy to look this over myself as soon as I can and send the fixes.

**Pull request merged**
