### PR TITLE
Switch to using cycle-history for history interaction

### PR DESCRIPTION
**Pull request by bruz**
I'm new to Cycle.js and thought adding cycle-history might be a nice exercise when I spotted [this issue](https://github.com/cyclejs/todomvc-cycle/issues/26). Any feedback is welcome since I'm new and it wouldn't be shocking if there is a better way to go about this.

### CODE REVIEW

**Comment by lius** [comment]
IMHO, I do not see cyclejs incorporating a history or routing library soon, so I think it would be good to keep the "official" example with raw implementation and add alternatives, for example, as branches.
In particular, I see the cyclic-router as a better option (higher level of abstraction and fit with the framework development model) and it is gaining more and adoption of the community, so makes sense have a implementation with it.

**Comment by staltz** [comment]
This looks rather good to me. @TylorS do you think this is appropriate use of cycle-history?

**Comment by TylorS** [comment]
This looks good to me, but it uses an out of date version of cycle-history. If that's okay for now, I'd say it's good to merge :+1:

**Comment by staltz** [comment]
Ok, thanks for reviewing so quickly. I'll check if this runs normally, and then merge. Thanks @bruz and sorry for taking so long for me to review

**Pull request merged**
